name: Validate Environment

on:
  workflow_dispatch:
  push:

jobs:
  validate-environments:
    name: Check Environments
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [test, dev]
    steps:
      - name: Validate environment exists and has required reviewers
        env:
          GITHUB_TOKEN: ${{ github.token }}
          ENVIRONMENT_NAME: ${{ matrix.environment }}
        run: |
          echo "Validating environment: ${ENVIRONMENT_NAME}"
          # Query the environment via REST API
          response=$(curl -sSL \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/skruijt-foreflight/github-actions-sandbox/environments" \
          )
      
          echo $response

          # Use jq to scan the 'environments' array for an entry with .name == ${ENVIRONMENT_NAME}
          found_name=$(echo "$response" | jq -r --arg env "${ENVIRONMENT_NAME}" '
          .environments[]?
          | select(.name == $env)
          | .name
          ')
          
          if [ -z "$found_name" ]; then
            echo "ERROR: Environment '${ENVIRONMENT_NAME}' was not found in the environments array."
            exit 1
          else
            echo "SUCCESS: Found environment '$found_name' in the environments array."
          fi
